import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_ce_flutter/adapters.dart';
import 'package:just_audio_background/just_audio_background.dart';

import 'app.dart';
import 'domain/entities/eq_preset.dart';
import 'domain/entities/playlist.dart';
import 'domain/entities/song.dart';

Future<void>  main()async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Lock orientation to portrait
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // 2. Make status bar transparent so our dark UI bleeds edge-to-edge
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light, // white icons on dark bg
      systemNavigationBarColor: Color(0xFF0A0A0A),
      systemNavigationBarIconBrightness: Brightness.light,
    ),
  );
  await JustAudioBackground.init(
    androidNotificationChannelId: 'com.melox.audio',
    androidNotificationChannelName: 'Melox Audio',
    androidNotificationOngoing: true,       // can't swipe away while playing
    androidShowNotificationBadge: true,
    androidNotificationIcon: 'drawable/ic_notification', // we'll add this later
    preloadArtwork: true,
  );

  // 1. Init Hive — finds the app's documents directory on Android
  await Hive.initFlutter();

  // 2. Register type adapters (generated by build_runner)
  Hive.registerAdapter(SongAdapter());
  Hive.registerAdapter(PlaylistAdapter());
  Hive.registerAdapter(EQPresetAdapter());
  await Hive.openBox<Song>('songs');
  await Hive.openBox<Playlist>('playlists');
  await Hive.openBox<EQPreset>('eq_presets');
  await Future.wait([
    Hive.openBox<Song>('songs'),
    Hive.openBox<Playlist>('playlists'),
    Hive.openBox<EQPreset>('eq_presets'),
    Hive.openBox('settings'),
  ]);

  // 7. Seed built-in EQ presets on very first launch
  await _seedEQPresets();
  runApp(
    const ProviderScope(   // Riverpod needs this at the root
      child: MeloxApp(),
    ),
  );
}
Future<void> _seedEQPresets() async {
  final box = Hive.box<EQPreset>('eq_presets');

  // Only seed if box is empty (first launch)
  if (box.isNotEmpty) return;

  await box.addAll([
    EQPreset.flat(),
    EQPreset.bassBoost(),
    EQPreset.vocal(),
    EQPreset(
      name: 'Rock',
      bandLevels: [400, 200, -100, 200, 400],
      isBuiltIn: true,
    ),
    EQPreset(
      name: 'Electronic',
      bandLevels: [500, 300, 0, 300, 500],
      isBuiltIn: true,
    ),
    EQPreset(
      name: 'Jazz',
      bandLevels: [300, 0, 200, 0, 300],
      isBuiltIn: true,
    ),
  ]);
}

